name: Kernel Config - A13 5.15

permissions:
  contents: write # Allow writing to repository contents
  actions: write # Allows triggering actions

on:
  workflow_call:
    inputs:
      ksu_variant:
        required: true
        type: string
      ksu_commit:
        required: false
        type: string
      build_bypass:
        required: true
        type: boolean

jobs:
  build-kernels-a13-5-15:
    name: "5.15.${{ matrix.sub_level }}-${{ matrix.os_patch_level }}"
    strategy:
      fail-fast: false
      matrix:
        include:
        - sub_level: "167"
          os_patch_level: "2024-09"
        - sub_level: "X"
          os_patch_level: "lts"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android13"
      kernel_version: "5.15"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      ksu_variant: ${{ inputs.ksu_variant }}
      ksu_commit: ${{ inputs.ksu_commit }}
      build_bypass: ${{ inputs.build_bypass }}
